# 欢迎使用 Jekyll！
#
# 此配置文件用于影响整个博客的设置，这些值通常在设置一次后很少会编辑。如果你发现自己经常编辑此文件，请考虑使用 Jekyll 的数据文件功能来处理需要经常更新的数据。
#
# 由于技术原因，当你使用“bundle exec jekyll serve”时，此文件不会自动重新加载。如果你更改了此文件，请重启服务器进程。
#
# 如果您需要有关 YAML 语法的帮助，这里有一些快速参考供您参考：
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# 网站设置
# 这些设置用于个性化您的新网站。如果你查看 HTML 文件，你会看到它们通过 {{ site.title }}, {{ site.email }} 等方式进行访问。
# 您可以创建任何您想要的自定义变量，并且可以通过 {{ site.myvariable }} 在模板中访问它们。

title: pthmz's Blog
# email: your-email@example.com
description: >- # 这意味着忽略换行符，直到 "baseurl:"
  在此处为您的新网站撰写精彩的描述。您可以在 _config.yml 中编辑此行。它将显示在您的文档 head meta 中以及您的 feed.xml 网站描述中。
baseurl: "" # 您网站的子路径，例如 /blog
url: "https://pthmz.github.io" # 您网站的基本主机名和协议，例如 http://example.com
# twitter_username: jekyllrb
github_username: pthmz

# 构建设置
theme: minima
plugins:
  - jekyll-feed

# 排除不处理的内容。
# 默认情况下，以下内容不会被处理。
# 在 `exclude:` 键下列出的任何项目都将自动添加到内部的“默认列表”中。
#
# 排除的项目可以通过在 `include:` 列表中明确列出目录或其条目文件路径来进行处理。
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/